services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app_laravel
    volumes:
      - .:/var/www
      
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_laravel
    ports:
      - 8000:80
    working_dir: /var/www
    environment:
      FASTCGI_PASS: app:9000
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: postgres_laravel
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./src/.env
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'

  db_test:
      image: postgres:16
      container_name: postgres_laravel_test
      ports:
        - '5433:5432'
      volumes:
        - postgres_data_test:/var/lib/postgresql/data
      env_file:
        - ./src/.env.testing
      environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres_data: # 永続化用のボリュームを定義
  postgres_data_test:
